<?php
/**
 * Created by PhpStorm.
 * Author: Soe Thandar Aung
 * Date: 11/2/2016
 * Time: 2:19 PM
 */

use Illuminate\Database\Seeder;

class Default_RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('core_permission_role')->delete();

        $roles = array(
            ['role_id'=>1, 'permission_id'=>1],
            ['role_id'=>1, 'permission_id'=>2],
            ['role_id'=>1, 'permission_id'=>3],
            ['role_id'=>1, 'permission_id'=>4],
            ['role_id'=>1, 'permission_id'=>5],
            ['role_id'=>1, 'permission_id'=>6],
            ['role_id'=>1, 'permission_id'=>7],
            ['role_id'=>1, 'permission_id'=>8],
            ['role_id'=>1, 'permission_id'=>9],
            ['role_id'=>1, 'permission_id'=>10],
            ['role_id'=>1, 'permission_id'=>11],
            ['role_id'=>1, 'permission_id'=>12],
            ['role_id'=>1, 'permission_id'=>13],
            ['role_id'=>1, 'permission_id'=>14],
            ['role_id'=>1, 'permission_id'=>15],
            ['role_id'=>1, 'permission_id'=>16],
            ['role_id'=>1, 'permission_id'=>17],
            ['role_id'=>1, 'permission_id'=>18],
            ['role_id'=>1, 'permission_id'=>19],
            ['role_id'=>1, 'permission_id'=>20],
            ['role_id'=>1, 'permission_id'=>21],
            ['role_id'=>1, 'permission_id'=>22],
            ['role_id'=>1, 'permission_id'=>23],

            ['role_id'=>1, 'permission_id'=>30],
            ['role_id'=>1, 'permission_id'=>31],
            ['role_id'=>1, 'permission_id'=>32],
            ['role_id'=>1, 'permission_id'=>33],
            ['role_id'=>1, 'permission_id'=>34],
            ['role_id'=>1, 'permission_id'=>35],
            ['role_id'=>1, 'permission_id'=>36],
            ['role_id'=>1, 'permission_id'=>37],
            ['role_id'=>1, 'permission_id'=>38],
            ['role_id'=>1, 'permission_id'=>39],
            ['role_id'=>1, 'permission_id'=>40],
            ['role_id'=>1, 'permission_id'=>41],
            ['role_id'=>1, 'permission_id'=>42],
            ['role_id'=>1, 'permission_id'=>43],
            ['role_id'=>1, 'permission_id'=>44],

            //Country
            ['role_id'=>1, 'permission_id'=>50],
            ['role_id'=>1, 'permission_id'=>51],
            ['role_id'=>1, 'permission_id'=>52],
            ['role_id'=>1, 'permission_id'=>53],
            ['role_id'=>1, 'permission_id'=>54],
            ['role_id'=>1, 'permission_id'=>55],

            //Township
            ['role_id'=>1, 'permission_id'=>60],
            ['role_id'=>1, 'permission_id'=>61],
            ['role_id'=>1, 'permission_id'=>62],
            ['role_id'=>1, 'permission_id'=>63],
            ['role_id'=>1, 'permission_id'=>64],
            ['role_id'=>1, 'permission_id'=>65],

            //City
            ['role_id'=>1, 'permission_id'=>70],
            ['role_id'=>1, 'permission_id'=>71],
            ['role_id'=>1, 'permission_id'=>72],
            ['role_id'=>1, 'permission_id'=>73],
            ['role_id'=>1, 'permission_id'=>74],
            ['role_id'=>1, 'permission_id'=>75],
            //Popular City
            ['role_id'=>1, 'permission_id'=>76],
            ['role_id'=>1, 'permission_id'=>77],

            //Features
            ['role_id'=>1, 'permission_id'=>80],
            ['role_id'=>1, 'permission_id'=>81],
            ['role_id'=>1, 'permission_id'=>82],
            ['role_id'=>1, 'permission_id'=>83],
            ['role_id'=>1, 'permission_id'=>84],
            ['role_id'=>1, 'permission_id'=>85],

            //Amenities
            ['role_id'=>1, 'permission_id'=>90],
            ['role_id'=>1, 'permission_id'=>91],
            ['role_id'=>1, 'permission_id'=>92],
            ['role_id'=>1, 'permission_id'=>93],
            ['role_id'=>1, 'permission_id'=>94],
            ['role_id'=>1, 'permission_id'=>95],

            //Facilities
            ['role_id'=>1, 'permission_id'=>100],
            ['role_id'=>1, 'permission_id'=>101],
            ['role_id'=>1, 'permission_id'=>102],
            ['role_id'=>1, 'permission_id'=>103],
            ['role_id'=>1, 'permission_id'=>104],
            ['role_id'=>1, 'permission_id'=>105],

            //Hotel Restaurant Category
            ['role_id'=>1, 'permission_id'=>110],
            ['role_id'=>1, 'permission_id'=>111],
            ['role_id'=>1, 'permission_id'=>112],
            ['role_id'=>1, 'permission_id'=>113],
            ['role_id'=>1, 'permission_id'=>114],
            ['role_id'=>1, 'permission_id'=>115],

            //Room Category Amenities
            ['role_id'=>1, 'permission_id'=>120],
            ['role_id'=>1, 'permission_id'=>121],
            ['role_id'=>1, 'permission_id'=>122],
            ['role_id'=>1, 'permission_id'=>123],
            ['role_id'=>1, 'permission_id'=>124],
            ['role_id'=>1, 'permission_id'=>125],

            //Jquery Validation for Country and Township
            ['role_id'=>1, 'permission_id'=>130],
            ['role_id'=>1, 'permission_id'=>131],

            //Room View
            ['role_id'=>1, 'permission_id'=>140],
            ['role_id'=>1, 'permission_id'=>141],
            ['role_id'=>1, 'permission_id'=>142],
            ['role_id'=>1, 'permission_id'=>143],
            ['role_id'=>1, 'permission_id'=>144],
            ['role_id'=>1, 'permission_id'=>145],

            //Hotel
            ['role_id'=>1, 'permission_id'=>150],
            ['role_id'=>1, 'permission_id'=>151],
            ['role_id'=>1, 'permission_id'=>152],
            ['role_id'=>1, 'permission_id'=>153],
            ['role_id'=>1, 'permission_id'=>154],
            ['role_id'=>1, 'permission_id'=>155],
            //Recommend Hotel
            ['role_id'=>1, 'permission_id'=>156],
            ['role_id'=>1, 'permission_id'=>157],

            //Hotel Room Type
            ['role_id'=>1, 'permission_id'=>160],
            ['role_id'=>1, 'permission_id'=>161],
            ['role_id'=>1, 'permission_id'=>162],
            ['role_id'=>1, 'permission_id'=>163],
            ['role_id'=>1, 'permission_id'=>164],
            ['role_id'=>1, 'permission_id'=>165],

            //Hotel Room Category
            ['role_id'=>1, 'permission_id'=>170],
            ['role_id'=>1, 'permission_id'=>171],
            ['role_id'=>1, 'permission_id'=>172],
            ['role_id'=>1, 'permission_id'=>173],
            ['role_id'=>1, 'permission_id'=>174],
            ['role_id'=>1, 'permission_id'=>175],

            //Room
            ['role_id'=>1, 'permission_id'=>180],
            ['role_id'=>1, 'permission_id'=>181],
            ['role_id'=>1, 'permission_id'=>182],
            ['role_id'=>1, 'permission_id'=>183],
            ['role_id'=>1, 'permission_id'=>184],
            ['role_id'=>1, 'permission_id'=>185],

            //Room Category Facilities
            ['role_id'=>1, 'permission_id'=>190],
            ['role_id'=>1, 'permission_id'=>191],
            ['role_id'=>1, 'permission_id'=>192],
            ['role_id'=>1, 'permission_id'=>193],
            ['role_id'=>1, 'permission_id'=>194],
            ['role_id'=>1, 'permission_id'=>195],

            //Hotel Feature
            ['role_id'=>1, 'permission_id'=>200],
            ['role_id'=>1, 'permission_id'=>201],
            ['role_id'=>1, 'permission_id'=>202],
            ['role_id'=>1, 'permission_id'=>203],
            ['role_id'=>1, 'permission_id'=>204],
            ['role_id'=>1, 'permission_id'=>205],

            //Room Discount
            ['role_id'=>1, 'permission_id'=>210],
            ['role_id'=>1, 'permission_id'=>211],
            ['role_id'=>1, 'permission_id'=>212],
            ['role_id'=>1, 'permission_id'=>213],
            ['role_id'=>1, 'permission_id'=>214],
            ['role_id'=>1, 'permission_id'=>215],

            //Room Blackout Period
            ['role_id'=>1, 'permission_id'=>220],
            ['role_id'=>1, 'permission_id'=>221],
            ['role_id'=>1, 'permission_id'=>222],
            ['role_id'=>1, 'permission_id'=>223],
            ['role_id'=>1, 'permission_id'=>224],
            ['role_id'=>1, 'permission_id'=>225],

            //Room Available Period
            ['role_id'=>1, 'permission_id'=>230],
            ['role_id'=>1, 'permission_id'=>231],
            ['role_id'=>1, 'permission_id'=>232],
            ['role_id'=>1, 'permission_id'=>233],
            ['role_id'=>1, 'permission_id'=>234],
            ['role_id'=>1, 'permission_id'=>235],

            //Hotel Nearby Airport
            ['role_id'=>1, 'permission_id'=>240],
            ['role_id'=>1, 'permission_id'=>241],
            ['role_id'=>1, 'permission_id'=>242],
            ['role_id'=>1, 'permission_id'=>243],
            ['role_id'=>1, 'permission_id'=>244],
            ['role_id'=>1, 'permission_id'=>245],

            //Hotel Nearby Station
            ['role_id'=>1, 'permission_id'=>250],
            ['role_id'=>1, 'permission_id'=>251],
            ['role_id'=>1, 'permission_id'=>252],
            ['role_id'=>1, 'permission_id'=>253],
            ['role_id'=>1, 'permission_id'=>254],
            ['role_id'=>1, 'permission_id'=>255],

            //Hotel Nearby Hospital
            ['role_id'=>1, 'permission_id'=>260],
            ['role_id'=>1, 'permission_id'=>261],
            ['role_id'=>1, 'permission_id'=>262],
            ['role_id'=>1, 'permission_id'=>263],
            ['role_id'=>1, 'permission_id'=>264],
            ['role_id'=>1, 'permission_id'=>265],

            //Hotel Nearby Convenience Store
            ['role_id'=>1, 'permission_id'=>270],
            ['role_id'=>1, 'permission_id'=>271],
            ['role_id'=>1, 'permission_id'=>272],
            ['role_id'=>1, 'permission_id'=>273],
            ['role_id'=>1, 'permission_id'=>274],
            ['role_id'=>1, 'permission_id'=>275],

            //Hotel Nearby Drug Store
            ['role_id'=>1, 'permission_id'=>280],
            ['role_id'=>1, 'permission_id'=>281],
            ['role_id'=>1, 'permission_id'=>282],
            ['role_id'=>1, 'permission_id'=>283],
            ['role_id'=>1, 'permission_id'=>284],
            ['role_id'=>1, 'permission_id'=>285],

            //Facility Group
            ['role_id'=>1, 'permission_id'=>290],
            ['role_id'=>1, 'permission_id'=>291],
            ['role_id'=>1, 'permission_id'=>292],
            ['role_id'=>1, 'permission_id'=>293],
            ['role_id'=>1, 'permission_id'=>294],
            ['role_id'=>1, 'permission_id'=>295],

            //Hotel Restaurant
            ['role_id'=>1, 'permission_id'=>300],
            ['role_id'=>1, 'permission_id'=>301],
            ['role_id'=>1, 'permission_id'=>302],
            ['role_id'=>1, 'permission_id'=>303],
            ['role_id'=>1, 'permission_id'=>304],
            ['role_id'=>1, 'permission_id'=>305],

            //Hotel Facility
            ['role_id'=>1, 'permission_id'=>310],
            ['role_id'=>1, 'permission_id'=>311],
            ['role_id'=>1, 'permission_id'=>312],
            ['role_id'=>1, 'permission_id'=>313],
            ['role_id'=>1, 'permission_id'=>314],
            ['role_id'=>1, 'permission_id'=>315],

            //Landmark
            ['role_id'=>1, 'permission_id'=>320],
            ['role_id'=>1, 'permission_id'=>321],
            ['role_id'=>1, 'permission_id'=>322],
            ['role_id'=>1, 'permission_id'=>323],
            ['role_id'=>1, 'permission_id'=>324],
            ['role_id'=>1, 'permission_id'=>325],

            //Hotel Landmark
            ['role_id'=>1, 'permission_id'=>330],
            ['role_id'=>1, 'permission_id'=>331],
            ['role_id'=>1, 'permission_id'=>332],
            ['role_id'=>1, 'permission_id'=>333],
            ['role_id'=>1, 'permission_id'=>334],
            ['role_id'=>1, 'permission_id'=>335],

            //Room Category Amenities
            ['role_id'=>1, 'permission_id'=>340],
            ['role_id'=>1, 'permission_id'=>341],
            ['role_id'=>1, 'permission_id'=>342],
            ['role_id'=>1, 'permission_id'=>343],
            ['role_id'=>1, 'permission_id'=>344],
            ['role_id'=>1, 'permission_id'=>345],

            //Hotel Config
            ['role_id'=>1, 'permission_id'=>350],
            ['role_id'=>1, 'permission_id'=>351],
            ['role_id'=>1, 'permission_id'=>352],
            ['role_id'=>1, 'permission_id'=>353],
            ['role_id'=>1, 'permission_id'=>354],
            ['role_id'=>1, 'permission_id'=>355],

            //SaleSummary Report
            ['role_id'=>1, 'permission_id'=>360],
            ['role_id'=>1, 'permission_id'=>361],
            ['role_id'=>1, 'permission_id'=>362],

            //Booking Report
            ['role_id'=>1, 'permission_id'=>370],
            ['role_id'=>1, 'permission_id'=>371],
            ['role_id'=>1, 'permission_id'=>372],
            ['role_id'=>1, 'permission_id'=>373],



            //Backend Multi_Language
            ['role_id'=>1, 'permission_id'=>500],

            ['role_id'=>233, 'permission_id'=>501],
            ['role_id'=>235, 'permission_id'=>502],
            ['role_id'=>236, 'permission_id'=>503],
            ['role_id'=>237, 'permission_id'=>504],
            ['role_id'=>239, 'permission_id'=>505],
            ['role_id'=>240, 'permission_id'=>506],
            ['role_id'=>241, 'permission_id'=>510],
            ['role_id'=>242, 'permission_id'=>511],
            ['role_id'=>243, 'permission_id'=>512],
            ['role_id'=>244, 'permission_id'=>513],
            ['role_id'=>245, 'permission_id'=>514],
            ['role_id'=>246, 'permission_id'=>515],
            ['role_id'=>247, 'permission_id'=>520],
            ['role_id'=>248, 'permission_id'=>521],
            ['role_id'=>249, 'permission_id'=>522],
            ['role_id'=>250, 'permission_id'=>523],
            ['role_id'=>251, 'permission_id'=>524],
            ['role_id'=>252, 'permission_id'=>525],


            //For Admin
            ['role_id'=>2, 'permission_id'=>531],
            ['role_id'=>2, 'permission_id'=>532],
            ['role_id'=>2, 'permission_id'=>533],
            ['role_id'=>2, 'permission_id'=>534],
            ['role_id'=>2, 'permission_id'=>535],
            ['role_id'=>2, 'permission_id'=>536],
            ['role_id'=>2, 'permission_id'=>537],
            ['role_id'=>2, 'permission_id'=>538],
            ['role_id'=>2, 'permission_id'=>539],
            ['role_id'=>2, 'permission_id'=>540],
            ['role_id'=>2, 'permission_id'=>541],
            ['role_id'=>2, 'permission_id'=>542],
            ['role_id'=>2, 'permission_id'=>543],
            ['role_id'=>2, 'permission_id'=>544],
            ['role_id'=>2, 'permission_id'=>545],
            ['role_id'=>2, 'permission_id'=>546],
            ['role_id'=>2, 'permission_id'=>547],
            ['role_id'=>2, 'permission_id'=>548],
            ['role_id'=>2, 'permission_id'=>549],
            ['role_id'=>2, 'permission_id'=>550],
            ['role_id'=>2, 'permission_id'=>551],
            ['role_id'=>2, 'permission_id'=>552],
            ['role_id'=>2, 'permission_id'=>553],
            ['role_id'=>2, 'permission_id'=>560],
            ['role_id'=>2, 'permission_id'=>561],
            ['role_id'=>2, 'permission_id'=>562],
            ['role_id'=>2, 'permission_id'=>563],
            ['role_id'=>2, 'permission_id'=>564],
            ['role_id'=>2, 'permission_id'=>565],
            ['role_id'=>2, 'permission_id'=>566],
            ['role_id'=>2, 'permission_id'=>567],
            ['role_id'=>2, 'permission_id'=>568],
            ['role_id'=>2, 'permission_id'=>569],
            ['role_id'=>2, 'permission_id'=>570],
            ['role_id'=>2, 'permission_id'=>571],
            ['role_id'=>2, 'permission_id'=>572],
            ['role_id'=>2, 'permission_id'=>573],
            ['role_id'=>2, 'permission_id'=>574],
            ['role_id'=>2, 'permission_id'=>580],
            ['role_id'=>2, 'permission_id'=>581],
            ['role_id'=>2, 'permission_id'=>582],
            ['role_id'=>2, 'permission_id'=>583],
            ['role_id'=>2, 'permission_id'=>584],
            ['role_id'=>2, 'permission_id'=>585],
            ['role_id'=>2, 'permission_id'=>590],
            ['role_id'=>2, 'permission_id'=>591],
            ['role_id'=>2, 'permission_id'=>592],
            ['role_id'=>2, 'permission_id'=>593],
            ['role_id'=>2, 'permission_id'=>594],
            ['role_id'=>2, 'permission_id'=>595],
            ['role_id'=>2, 'permission_id'=>600],
            ['role_id'=>2, 'permission_id'=>601],
            ['role_id'=>2, 'permission_id'=>602],
            ['role_id'=>2, 'permission_id'=>603],
            ['role_id'=>2, 'permission_id'=>604],
            ['role_id'=>2, 'permission_id'=>605],
            ['role_id'=>2, 'permission_id'=>606],
            ['role_id'=>2, 'permission_id'=>607],
            ['role_id'=>2, 'permission_id'=>610],
            ['role_id'=>2, 'permission_id'=>611],
            ['role_id'=>2, 'permission_id'=>612],
            ['role_id'=>2, 'permission_id'=>613],
            ['role_id'=>2, 'permission_id'=>614],
            ['role_id'=>2, 'permission_id'=>615],
            ['role_id'=>2, 'permission_id'=>620],
            ['role_id'=>2, 'permission_id'=>621],
            ['role_id'=>2, 'permission_id'=>622],
            ['role_id'=>2, 'permission_id'=>623],
            ['role_id'=>2, 'permission_id'=>624],
            ['role_id'=>2, 'permission_id'=>625],
            ['role_id'=>2, 'permission_id'=>630],
            ['role_id'=>2, 'permission_id'=>631],
            ['role_id'=>2, 'permission_id'=>632],
            ['role_id'=>2, 'permission_id'=>633],
            ['role_id'=>2, 'permission_id'=>634],
            ['role_id'=>2, 'permission_id'=>635],
            ['role_id'=>2, 'permission_id'=>640],
            ['role_id'=>2, 'permission_id'=>641],
            ['role_id'=>2, 'permission_id'=>642],
            ['role_id'=>2, 'permission_id'=>643],
            ['role_id'=>2, 'permission_id'=>644],
            ['role_id'=>2, 'permission_id'=>645],
            ['role_id'=>2, 'permission_id'=>650],
            ['role_id'=>2, 'permission_id'=>651],
            ['role_id'=>2, 'permission_id'=>652],
            ['role_id'=>2, 'permission_id'=>653],
            ['role_id'=>2, 'permission_id'=>654],
            ['role_id'=>2, 'permission_id'=>655],
            ['role_id'=>2, 'permission_id'=>660],
            ['role_id'=>2, 'permission_id'=>661],
            ['role_id'=>2, 'permission_id'=>670],
            ['role_id'=>2, 'permission_id'=>671],
            ['role_id'=>2, 'permission_id'=>672],
            ['role_id'=>2, 'permission_id'=>673],
            ['role_id'=>2, 'permission_id'=>674],
            ['role_id'=>2, 'permission_id'=>675],
            ['role_id'=>2, 'permission_id'=>680],
            ['role_id'=>2, 'permission_id'=>681],
            ['role_id'=>2, 'permission_id'=>682],
            ['role_id'=>2, 'permission_id'=>683],
            ['role_id'=>2, 'permission_id'=>684],
            ['role_id'=>2, 'permission_id'=>685],
            ['role_id'=>2, 'permission_id'=>686],
            ['role_id'=>2, 'permission_id'=>687],
            ['role_id'=>2, 'permission_id'=>690],
            ['role_id'=>2, 'permission_id'=>691],
            ['role_id'=>2, 'permission_id'=>692],
            ['role_id'=>2, 'permission_id'=>693],
            ['role_id'=>2, 'permission_id'=>694],
            ['role_id'=>2, 'permission_id'=>695],
            ['role_id'=>2, 'permission_id'=>700],
            ['role_id'=>2, 'permission_id'=>701],
            ['role_id'=>2, 'permission_id'=>702],
            ['role_id'=>2, 'permission_id'=>703],
            ['role_id'=>2, 'permission_id'=>704],
            ['role_id'=>2, 'permission_id'=>705],
            ['role_id'=>2, 'permission_id'=>710],
            ['role_id'=>2, 'permission_id'=>711],
            ['role_id'=>2, 'permission_id'=>712],
            ['role_id'=>2, 'permission_id'=>713],
            ['role_id'=>2, 'permission_id'=>714],
            ['role_id'=>2, 'permission_id'=>715],
            ['role_id'=>2, 'permission_id'=>720],
            ['role_id'=>2, 'permission_id'=>721],
            ['role_id'=>2, 'permission_id'=>722],
            ['role_id'=>2, 'permission_id'=>723],
            ['role_id'=>2, 'permission_id'=>724],
            ['role_id'=>2, 'permission_id'=>725],
            ['role_id'=>2, 'permission_id'=>730],
            ['role_id'=>2, 'permission_id'=>731],
            ['role_id'=>2, 'permission_id'=>732],
            ['role_id'=>2, 'permission_id'=>733],
            ['role_id'=>2, 'permission_id'=>734],
            ['role_id'=>2, 'permission_id'=>735],
            ['role_id'=>2, 'permission_id'=>740],
            ['role_id'=>2, 'permission_id'=>741],
            ['role_id'=>2, 'permission_id'=>742],
            ['role_id'=>2, 'permission_id'=>743],
            ['role_id'=>2, 'permission_id'=>744],
            ['role_id'=>2, 'permission_id'=>745],
            ['role_id'=>2, 'permission_id'=>750],
            ['role_id'=>2, 'permission_id'=>751],
            ['role_id'=>2, 'permission_id'=>752],
            ['role_id'=>2, 'permission_id'=>753],
            ['role_id'=>2, 'permission_id'=>754],
            ['role_id'=>2, 'permission_id'=>755],
            ['role_id'=>2, 'permission_id'=>760],
            ['role_id'=>2, 'permission_id'=>761],
            ['role_id'=>2, 'permission_id'=>762],
            ['role_id'=>2, 'permission_id'=>763],
            ['role_id'=>2, 'permission_id'=>764],
            ['role_id'=>2, 'permission_id'=>765],
            ['role_id'=>2, 'permission_id'=>770],
            ['role_id'=>2, 'permission_id'=>771],
            ['role_id'=>2, 'permission_id'=>772],
            ['role_id'=>2, 'permission_id'=>773],
            ['role_id'=>2, 'permission_id'=>774],
            ['role_id'=>2, 'permission_id'=>775],
            ['role_id'=>2, 'permission_id'=>780],
            ['role_id'=>2, 'permission_id'=>781],
            ['role_id'=>2, 'permission_id'=>782],
            ['role_id'=>2, 'permission_id'=>783],
            ['role_id'=>2, 'permission_id'=>784],
            ['role_id'=>2, 'permission_id'=>785],
            ['role_id'=>2, 'permission_id'=>790],
            ['role_id'=>2, 'permission_id'=>791],
            ['role_id'=>2, 'permission_id'=>792],
            ['role_id'=>2, 'permission_id'=>793],
            ['role_id'=>2, 'permission_id'=>794],
            ['role_id'=>2, 'permission_id'=>795],
            ['role_id'=>2, 'permission_id'=>800],
            ['role_id'=>2, 'permission_id'=>801],
            ['role_id'=>2, 'permission_id'=>802],
            ['role_id'=>2, 'permission_id'=>803],
            ['role_id'=>2, 'permission_id'=>804],
            ['role_id'=>2, 'permission_id'=>805],
            ['role_id'=>2, 'permission_id'=>810],
            ['role_id'=>2, 'permission_id'=>811],
            ['role_id'=>2, 'permission_id'=>812],
            ['role_id'=>2, 'permission_id'=>813],
            ['role_id'=>2, 'permission_id'=>814],
            ['role_id'=>2, 'permission_id'=>815],
            ['role_id'=>2, 'permission_id'=>820],
            ['role_id'=>2, 'permission_id'=>821],
            ['role_id'=>2, 'permission_id'=>822],
            ['role_id'=>2, 'permission_id'=>823],
            ['role_id'=>2, 'permission_id'=>824],
            ['role_id'=>2, 'permission_id'=>825],
            ['role_id'=>2, 'permission_id'=>830],
            ['role_id'=>2, 'permission_id'=>831],
            ['role_id'=>2, 'permission_id'=>832],
            ['role_id'=>2, 'permission_id'=>833],
            ['role_id'=>2, 'permission_id'=>834],
            ['role_id'=>2, 'permission_id'=>835],
            ['role_id'=>2, 'permission_id'=>840],
            ['role_id'=>2, 'permission_id'=>841],
            ['role_id'=>2, 'permission_id'=>842],
            ['role_id'=>2, 'permission_id'=>843],
            ['role_id'=>2, 'permission_id'=>844],
            ['role_id'=>2, 'permission_id'=>845],
            ['role_id'=>2, 'permission_id'=>850],
            ['role_id'=>2, 'permission_id'=>851],
            ['role_id'=>2, 'permission_id'=>852],
            ['role_id'=>2, 'permission_id'=>853],
            ['role_id'=>2, 'permission_id'=>854],
            ['role_id'=>2, 'permission_id'=>855],
            ['role_id'=>2, 'permission_id'=>860],
            ['role_id'=>2, 'permission_id'=>861],
            ['role_id'=>2, 'permission_id'=>862],
            ['role_id'=>2, 'permission_id'=>863],
            ['role_id'=>2, 'permission_id'=>864],
            ['role_id'=>2, 'permission_id'=>865],
            ['role_id'=>2, 'permission_id'=>870],
            ['role_id'=>2, 'permission_id'=>871],
            ['role_id'=>2, 'permission_id'=>872],
            ['role_id'=>2, 'permission_id'=>873],
            ['role_id'=>2, 'permission_id'=>874],
            ['role_id'=>2, 'permission_id'=>875],
            ['role_id'=>2, 'permission_id'=>880],
            ['role_id'=>2, 'permission_id'=>881],
            ['role_id'=>2, 'permission_id'=>882],
            ['role_id'=>2, 'permission_id'=>883],
            ['role_id'=>2, 'permission_id'=>884],
            ['role_id'=>2, 'permission_id'=>885],
            ['role_id'=>2, 'permission_id'=>890],
            ['role_id'=>2, 'permission_id'=>891],
            ['role_id'=>2, 'permission_id'=>892],
            ['role_id'=>2, 'permission_id'=>900],
            ['role_id'=>2, 'permission_id'=>901],
            ['role_id'=>2, 'permission_id'=>902],
            ['role_id'=>2, 'permission_id'=>903],
            ['role_id'=>2, 'permission_id'=>1030],
            ['role_id'=>2, 'permission_id'=>1031],
            ['role_id'=>2, 'permission_id'=>1032],
            ['role_id'=>2, 'permission_id'=>1033],
            ['role_id'=>2, 'permission_id'=>1034],
            ['role_id'=>2, 'permission_id'=>1035],
            ['role_id'=>2, 'permission_id'=>1036],
            ['role_id'=>2, 'permission_id'=>1040],
            ['role_id'=>2, 'permission_id'=>1041],
            ['role_id'=>2, 'permission_id'=>1042],
            ['role_id'=>2, 'permission_id'=>1043],
            ['role_id'=>2, 'permission_id'=>1044],
            ['role_id'=>2, 'permission_id'=>1045],
            ['role_id'=>2, 'permission_id'=>1050],
            ['role_id'=>2, 'permission_id'=>1051],
            ['role_id'=>2, 'permission_id'=>1052],
            ['role_id'=>2, 'permission_id'=>1053],
            ['role_id'=>2, 'permission_id'=>1054],
            ['role_id'=>2, 'permission_id'=>1055],

        );

        DB::table('core_permission_role')->insert($roles);
    }
}
